Settings:
  # 커맨드 사용시 표시되는 접두사 입니다.
  prefix: "&f[ &b칭호 &f] "

  # 해당 칭호를 기본 칭호로 설정하고 접속하는 모든 유저에게 해당 칭호를 지급합니다.
  # PrefixList에 존재하는 칭호 이름으로 설정해주세요.
  # DefaultPrefix: "치미창가"

  # 유저가 소유 가능한 최대 칭호 갯수 입니다.
  maxPrefix: 30

  # 쿠폰으로 발급할 아이템의 타입을 설정합니다.
  couponMaterial: PAPER
  # 리소스팩에 사용될 커스텀 모델 데이터를 설정합니다.
  couponCustomModelData: 0
  # 쿠폰으로 발급될 아이템의 이름을 설정합니다.
  couponCustomName: "&f[ &b칭호 쿠폰 &f] %lsp.prefix%"
  # 쿠폰으로 발급될 아이템의 로어를 설정합니다.
  couponLores:
    - "&f"
    - "%lsp.prefix%"
    - "&6우클릭시 칭호를 등록합니다."

  # 위 정보가 변경되어도 이미 발급된 쿠폰은 그대로 사용 가능합니다.

  PrefixList:
    치미창가: "&f[ &6치미창가! &f]"